### ISSUE TITLE
Add the repos present in this post in the list

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Beginner-Friendly-Repos-for-Hacktoberfest#10]
https://www.linkedin.com/posts/internfreak_github-codemistichacktoberfest-an-exclusive-activity-6983110074869137408-Uwil/?utm_source=share&utm_medium=member_desktop

**Comment by sculley** [comment]
Hello, please assign me this issue.

**Comment by arpit456jain** [comment]
sure
